MLShukai/ami-vconf24

- .github/workflows/pre-commit.yaml
- .github/workflows/test.yaml
- Dockerfile
- Makefile
- ami/data/buffers/base_data_buffer.py
- ami/data/buffers/buffer_names.py
- ami/data/buffers/causal_data_buffer.py
- ami/data/buffers/random_data_buffer.py
- ami/data/step_data.py
- ami/data/utils.py
- ami/models/model_names.py
- ami/models/utils.py
- ami/threads/shared_object_names.py
- pyproject.toml
- tests/data/buffers/test_base_data_buffer.py
- tests/helpers.py
Unity ML Agentsを用いる都合上 pythonのバージョンを3.10へダウングレードしました。
Dockerの変更もあります。
> Python3.10へダウングレード

- scripts/restart-vrchat.sh
> VRChatの再起動プログラムを修正

- ami/models/action_predictor.py
- ami/models/inverse_dynamics.py
- tests/models/test_action_predictor.py
- tests/models/test_inverse_dynamics.py
#4 InverseDynamicsのフレームワーククラスと、行動を予測するActionPredictorをPrimitiveAMIから移植しました。
去年の実装では連続値の行動テンソルを直接出力していましたが、LargeScaleCuriosityの実装に合わせてDistribution型としました。その関係で、DeterministicNormalという、決定的に`mean`のみを返し、固定した標準偏差で対数尤度を計算するモジュールを使用しています。
> 旧Observation Encoder `Inverse Dynamics Features`の実装

- Dockerfile
> Hydra Shell Completionを設定

- ami/models/forward_dynamics.py
- ami/trainers/forward_dynamics_trainer.py
- tests/models/test_forward_dynamics.py
- tests/trainers/test_forward_dynamics_trainer.py
#18 に関連して、ForwardDynamicsWithActionRewardを実装しました。
ほとんどForward Dynamicsのコピペですが、実験的なコードである側面を加味して **現段階では** 統一的なベースクラスを作ることを避けました。いつか ただの Forward Dynamicsを今回実装したクラスに移行しても良いかもしれないと思っています。
> 行動と報酬も出力するForwardDynamicsWithActionRewardクラスとそのTrainerを実装

- ami/interactions/fixed_interval_interaction.py
- ami/interactions/interaction.py
- ami/interactions/io_wrappers/base_io_wrapper.py
- ami/interactions/io_wrappers/function_wrapper.py
- tests/interactions/io_wrappers/test_function_io_wrapper.py
- tests/interactions/test_interaction.py
#6 Interactionクラスに観測/行動をラップする機能を実装しました。
#18 で行動をOnehotにする関係で、それを行動 IDに変換する必要があり、Observation/ActionWrapperをつける機能を実装しました。
当初は `BaseObservationWrapper`, `BaseActionWrapper`を 別々に実装することを考えていましたが、機能が完全に一致している上に、想定される機能拡張も同一と考えられるため `BaseIOWrapper`に統一しました。
また、簡単にラッパークラスを作れるように `FunctionIOWrapper`クラスを作成しました。
* Interaction
* FixedIntervalInteraction
デフォルトでラッパーには Noneを指定しているので設定ファイルの編集はありません。
> Interactionクラスに observation / action wrapperを実装

- ami/models/components/drop_path.py
- tests/models/components/test_drop_path.py
I-JEPAの実装時に必要となるモジュール`DropPath`とそのTestの追加
> 37_i_jepa_model_droppath

- ami/models/model_wrapper.py
- ami/models/vae.py
- configs/models/dreamer.yaml
- configs/models/image_vae.yaml
- configs/models/image_vae_sconv_discrete_ppo.yaml
- configs/models/world_models.yaml
- configs/models/world_models_sioconv.yaml
- configs/models/world_models_sioconv_lerp_hidden.yaml
- tests/models/test_model_wrapper.py
- tests/models/test_vae.py
- tests/trainers/test_forward_dynamics_trainer.py
- tests/trainers/test_image_vae_trainer.py
> ModelWrapperの`infer`を依存性抽出

- ami/models/i_jepa.py
- ami/models/utils.py
- ami/trainers/components/i_jepa_mask_collator.py
- configs/experiment/i_jepa.yaml
- configs/launch.yaml
- configs/models/i_jepa.yaml
- configs/trainers/i_jepa.yaml
- configs/trainers/i_jepa/default.yaml
- tests/models/test_i_jepa.py
- tests/models/test_utils.py
> I-JEPAの学習と推論で必要となるファイルの追加

- ami/models/components/stacked_features.py
- ami/models/policy_value_common_net.py
- tests/models/components/test_stacked_features.py
- tests/models/test_policy_value_common_net.py
> LerpStackedHiddenをLerpStackedFeaturesとして再実装

- ami/models/components/stacked_features.py
- tests/models/components/test_stacked_features.py
> `ToStackedFeatures`を追加

- ami/models/components/unet/encoder_block.py
- tests/models/components/unet/test_encoder_block.py
Diffusionで必要となる、Unetの構成要素の1つ`UnetEncoderBlock`の追加
> Unet_encoder_block

- ami/models/components/unet/decoder_block.py
- tests/models/components/unet/test_decoder_block.py
Diffusionで必要となる、Unetの構成要素の1つ`UnetDecoderBlock`の追加
> Unet_decoder_block

- ami/models/bool_mask_i_jepa.py
- ami/models/i_jepa.py
- configs/experiment/i_jepa_sioconv_dreamer_multi_step.yaml
- configs/experiment/i_jepa_sioconv_dreamer_multi_step_unity.yaml
- configs/models/i_jepa_sioconv_dreamer.yaml
- configs/trainers/dreaming_policy_value/default.yaml
- configs/trainers/i_jepa_forward_dynamics_dreaming.yaml
- tests/models/test_bool_mask_i_jepa.py
- tests/models/test_i_jepa.py
- tests/test_configs.py
#64 I-JEPAをImageEncoderとして用いた Agentを実装しました。
> I-JEPAをImageCuriosityAgentに組み込む 

- ami/threads/main_thread.py
- configs/launch.yaml
- configs/threads/default.yaml
- tests/threads/test_threads.py
実験に際して、システムの最大稼働時間を設定できると便利であると考えられるため、この機能を実装した。
> システムの最大稼働時間を設定可能に

- ami/interactions/io_wrappers/tensor_csv_recorder.py
- tests/interactions/io_wrappers/test_tensor_csv_recorder.py
> TensorCSVRecorderを実装

- configs/experiment/i_jepa_sioconv_ppodreamer_multi_step_medium.yaml
- configs/experiment/i_jepa_sioconv_ppodreamer_multi_step_small.yaml
I-JEPA, SioConv, PPODreamerのMedium, Smallサイズを追加しました。
> smallとmediumサイズを設定

- ami/interactions/environments/video_folders_image_observation_generator.py
- tests/interactions/environments/test_video_folders_image_observation_generator.py
#87 TensorVideoRecorderで記録した動画を読み込むためのクラスです。複数のフォルダ（エピソード）を指定する機能があります。
DummyEnvironmentのObservationGeneratorに渡して使用します。
> VideoFoldersImageObservationGeneratorクラスを実装

- ami/threads/background_thread.py
- ami/threads/inference_thread.py
- ami/threads/main_thread.py
- ami/threads/thread_control.py
- tests/threads/test_threads.py
バックグラウンドスレッドで例外が発生した場合にシステムを終了させる機能を実装しました。
また、その過程で `Interaction`の`terminate`が呼ばれないとActuatorのリセットがかからないといった問題が発生するため、try-finallyで解決を図りました。
> 例外発生時にSystemを終了する機能を実装

- ami/data/buffers/causal_data_buffer.py
- ami/data/buffers/random_data_buffer.py
- ami/trainers/bool_mask_i_jepa_trainer.py
- ami/trainers/dreaming_policy_value_trainer.py
- ami/trainers/forward_dynamics_trainer.py
- ami/trainers/i_jepa_trainer.py
- ami/trainers/image_vae_trainer.py
- ami/trainers/ppo_dreaming_policy_value_trainer.py
- tests/data/buffers/test_causal_data_buffer.py
- tests/data/buffers/test_random_data_buffer.py
- tests/trainers/test_bool_mask_i_jepa_trainer.py
- tests/trainers/test_dreaming_policy_value_trainer.py
- tests/trainers/test_forward_dynamics_trainer.py
- tests/trainers/test_i_jepa_trainer.py
- tests/trainers/test_image_vae_trainer.py
- tests/trainers/test_ppo_dreaming_policy_value_trainer.py
#95 PPOPolicyTrainer以外のすべてのTrainerに影響しました。
いい加減 DataBufferやTrainerまわりは共通化しないと変更にかかる工数が大変ですね。
> new_data_countを`count_data_added_since`へ変更

- ami/omegaconf_resolvers.py
- tests/test_omegaconf_resolvers.py
> globを実行するresolverを追加

- ami/threads/background_thread.py
- ami/threads/main_thread.py
- ami/threads/shared_object_names.py
- ami/threads/thread_control.py
- tests/threads/test_thread_control.py
- tests/threads/test_threads.py
> BackgroundThreadからMainThreadへの例外通知機能をThreadCommandHandlerから分離

- ami/models/model_wrapper.py
- tests/models/test_model_wrapper.py
> ModelWrapperにパラメータファイル読込機能を実装

- ami/interactions/io_wrappers/tensor_csv_recorder.py
- tests/interactions/io_wrappers/test_tensor_csv_recorder.py
#110 CSVに記録した行動を読み込むためのTensorCSVReaderクラスを実装しました。
> TensorCSVReaderを実装

- configs/experiment/i_jepa_sioconv_ppodreamer_multi_step.yaml
- configs/models/i_jepa_sioconv_ppodreamer.yaml
PPOPolicyではわざわざOneHot化する必要がないので修正した
> OneHotからDiscrete Policy Headへ変更

- ami/models/components/deterministic.py
- ami/models/csv_files_policy.py
- tests/models/components/test_deterministic.py
- tests/models/test_csv_files_policy.py
#110 CSVFileを読み込み、行動として出力する `CSVFilesPolicy`クラスを実装しました。
> CSVFilesPolicyを実装

- configs/experiment/learn_only_sioconv.yaml
- tests/test_configs.py
> 学習済のEncoder, Decoderのパラメータをセット

- configs/experiment/i_jepa_sioconv_ppodreamer_multi_step.yaml
- configs/experiment/learn_only_sioconv.yaml
#125 VRAMの余裕はほとんど増えなかったため、純粋に更新回数を増やしました。
> SioConvの学習でembed observationを直接使用し、更新回数を調整

- ami/utils.py
- tests/test_utils.py
min_max_normalization関数を実装しました。画像の可視化に使います。
> min_max_normalizationを実装

- configs/data_collectors/image_dynamics.yaml
- configs/experiment/learn_i_jepa_sioconv.yaml
- configs/models/learn_i_jepa_sioconv_large.yaml
- configs/trainers/i_jepa_forward_dynamics.yaml
- tests/test_configs.py
> I-JEPAとSioConvを同時に学習するconfigファイルを追加

- ami/models/i_jepa_latent_visualization_decoder.py
- ami/trainers/i_jepa_latent_visualization_trainer.py
- tests/trainers/test_i_jepa_latent_visualization_trainer.py
> IJEPADecoderの修正

- ami/models/components/mixture_desity_network.py
- ami/models/components/stacked_features.py
- tests/models/components/test_mixture_density_network.py
- tests/models/components/test_stacked_features.py
> MixtureDensityNetworkの選択確率分布の修正

- ami/interactions/environments/unity_environment.py
> 空いているbase_portを自動的に見つけるよう修正

- scripts/graph_plottings/bar_action_convergence.py
- scripts/graph_plottings/plot_i_jepa_results.py
- scripts/graph_plottings/plot_policy_results.py
- scripts/graph_plottings/plot_sioconv_results.py
- scripts/show_reconstruction.py
> 論文のグラフの作成スクリプトを作成

- ami/models/components/resnet.py
> ResnetFFにLayerNormとGELUを使用

- ami/models/components/audio_patchifier.py
- tests/models/components/test_audio_patchifier.py
> 音声をパッチ単位へと変換するモデルの追加

- ami/trainers/components/bool_audio_jepa_mask_collator.py
- tests/trainers/components/test_bool_audio_jepa_mask_collator.py
Audio-JEPAの学習を想定したCollatorの追加
同上
同上
> Audio-JEPA用Collator追加

- ami/interactions/environments/sensors/soundcard_audio_sensor.py
- pyproject.toml
- tests/interactions/environments/sensors/test_soundcard_audio_sensor.py
> SoundcardAudioSensorを実装

- ami/interactions/agents/observation_collecting_agent.py
- configs/experiment/bool_mask_i_jepa_with_videos.yaml
- configs/experiment/i_jepa_mean_patch_with_videos.yaml
- configs/interaction/agent/image_collecting.yaml
- configs/interaction/agent/observation_collecting.yaml
- tests/interactions/agents/test_image_collecting_agent.py
> ImageCollectingAgentをObservationCollectingAgentにリネーム

- ami/models/bool_mask_audio_jepa.py
- ami/models/components/positional_embeddings.py
- tests/models/test_bool_mask_audio_jepa.py
I-JEPAを音声に対応させたモデル`AudioJEPA`の実装
> I-JEPAを音声に対応させたモデル"AudioJEPA"の実装

- configs/experiment/i_jepa_sioconv_ppo_multi_step.yaml
- configs/interaction/environment/vrchat_image_discrete_1st_order_delay.yaml
delta time の値を修正、またいつも使用しているconfigの値を記述しました。
> configファイルの値を修正

- ami/interactions/environments/actuators/actuator_wrapper_from_io_wrapper.py
- ami/interactions/environments/sensors/sensor_wrapper_from_io_wrapper.py
- tests/interactions/environments/actuators/test_actuator_wrapper_from_io_wrapper.py
- tests/interactions/environments/sensors/test_sensor_wrapper_from_io_wrapper.py
#184 
これがマージされた場合、#179 はcloseします。
> IOWrapperをSensorWrapper/ActuatorWrapperとして使用できるクラスを実装

- ami/interactions/environments/actuators/vrchat_osc_discrete_actuator.py
> fix to stop 1st order delay actuator when system paused
