MLShukai/ami-vconf24

scripts/copy-vrchat-logs.sh
YAIBAにより取得した VRChatのワールド位置情報のログを プロジェクトディレクトリの `logs/vrchat-logs`にコピーするシェルスクリプトを追加しました。
LinuxにおけるVRChatのログ出力先の場所は特殊であり、毎度探すのが困難です。さらに、一定時間でログファイルが消えてしまう問題もあるため、コピーするシェルスクリプトを追加しました。
実行権限を与えているため、プロジェクトディレクトリで`./scripts/copy-vrchat-logs.sh`とするだけで実行できます。
=> vrchatのyaiba出力ログをコピーするshell scriptを追加

ami/models/components/one_hot.py, tests/models/components/test_one_hot.py
#18 に関連して、離散行動を扱う上で勾配を流せるようにする必要があったため、OneHotベクトルを使用し、勾配計算が可能なクラス群を追加しました。
mypyのバージョンアップでバグが修正された関係で Testがエラーになりますが、他のPRで直されるので無視してください。
* MaskedOneHotCategoricalStraightThrough: 既存のStraight Through Estimatorを使用したモデルにマスク機能を追加しました。これにより、アクション数が異なる複数種類のアクションを扱えるようになります。エントロピー計算式も追加しました。
* MultiOneHots: DiscretePolicyHeadの機能のOneHot版です。アクション数が異なる複数種類のアクションを出力する用です。
* OneHotToEmbedding: OneHotベクトルをEmbedding vectorに変換します。行列演算のため勾配が流れます。nn.Linearでも良かったんですが、bias項が常になかったりするので分かりやすさのために実装しました。
=> OneHotベクトルを処理するクラス群を追加

ami/models/components/fully_connected_normal.py, ami/models/model_names.py, ami/models/policy_or_value_network.py, tests/models/components/test_fully_connected_normal.py, tests/models/test_policy_or_value_network.py
#18 
Dreamerの学習を実装するために必要な 方策と価値関数のフレームワーククラスを実装した。
また、Dreamer V3において 価値関数が確率的に予測する実装になっていたため、それを実装するための`Normal`を出力するレイヤーも実装した。
=> PolicyとValueを実装するためのフレームワーク他を実装。

Dockerfile, Makefile
MacでもDocker環境を使えるようにしました。ただ、Mac上のLinuxはtime.sleepの精度がイマイチなのでいくつかテストが失敗します。`make run -k`と実行すると途中でエラー出ても続行するのでそちらを使いましょう。
Arm版のubuntu mirror サーバは高速なものに変更していますが、自らの責任で使用する必要があります。 https://jp.mirror.coganng.com/ubuntu/
=> MacOS上で`make docker-build`が通るように修正。

ami/data/buffers/buffer_names.py, ami/trainers/dreaming_policy_value_trainer.py, tests/trainers/test_dreaming_policy_value_trainer.py
#28 をまずマージしてください。
#18 Dreamer方式のPolicyとValueのTrainerを実装しました。
Dreamer V2以降では Policy Lossに方策勾配法も用いていますが、今回は Dreamer V1の収益最大化のみの実装です。
Random Data Bufferに初期状態（埋め込み観測と隠れ状態）を保存し、そこから空想上の軌道を生成します。
David HaらのWorld Modelsでは、Forward Dynamicsで未来観測を生成する際の不確実性（温度パラメータ）も存在したため、TrainerかMixtureDensityNetworkかに後に実装しようと思います。
収益が時間軸に対して総和を取る実装`sum(0)`になっている理由としては、収益は時間方向に対して減衰するため、収益を下手に時間方向でスケールさせてしまう`mean`は良くないのではないかと思ったためです。Dreamerの実装でも時間方向には和をとっているのでそうしました。
ただ、価値関数の損失は時間方向に依存しないので、時間方向も`mean`で損失を計算しています。
=> Dreamer方式の方策と価値関数のTrainerを実装

Makefile
今まで`make docker-build`を実行すると既存のイメージを上書きしてしまったり、他のユーザと永続ボリュームが干渉してしまっていた。そのためユーザ名を取得し、それをタグやsuffixにすることによって解消した。
=> Dockerのイメージとボリュームのタグにユーザ名を指定

ami/models/components/fully_connected_fixed_std_normal.py, ami/models/components/fully_connected_normal.py, ami/models/components/mixture_desity_network.py, tests/models/components/test_fully_connected_fixed_std_normal.py, tests/models/components/test_fully_connected_normal.py, tests/models/components/test_mixture_density_network.py
RewardやValue Headを予測する際に scalar次元であることが実装上求められるため、出力ヘッドの特徴量次元をsqueezeできる機能を実装した。特別にDistribution型を出力するレイヤーに対して適用したのは、Tensorが出力ではないため`forward`のoutputに対して行う操作が一律同じではなく、`squeeze`を内部的に実行しなければならないためである。
=> DistributionHeadクラスに `squeeze_feature_dim`のoptionを追加

ami/interactions/agents/curiosity_image_ppo_agent.py, tests/interactions/agents/test_curiosity_image_ppo_agent.py
#18 CuriosityPPOAgentを拡張しようかと思いましたが下手にコードを汚くするのでとりあえずコピペして、Forward Dynamics With Action Reward, Policy, Valueを使うAgentを実装しました。
コードの内容の関連性的に`curiosity_ppo_agent.py`に配置しています。将来的にうまく統合できたらします。
=> PolicyとValueが分離された場合の Curiosity Agentを実装

ami/models/components/mixture_desity_network.py, ami/trainers/dreaming_policy_value_trainer.py, configs/trainers/dreaming_policy_value/default.yaml, tests/models/components/test_mixture_density_network.py
#44 NormalMixtureが log_piを受け取る実装だと温度パラメータを動的に変更できないのでそこの仕様変更もしました。
=> Dreamerの学習時に予測の温度パラメータを指定可能に

ami/hydra_instantiators.py, ami/models/model_wrapper.py, ami/models/utils.py, tests/models/test_model_wrapper.py, tests/models/test_utils.py, tests/models/test_vae.py, tests/test_hydra_instantiators.py
I-JEPAなどの実装において、同一のモデルを別名で参照可能にする必要が発生したため、 モデルをInstantiateする際にエイリアスネームを設定可能にしました。
特に、`I_JEPA_TARGET_ENCODER`を、`IMAGE_ENCODER`という名前でアクセスする際に役立ちます。
片方は`Trainer`から、 片方は `Agent`クラスから参照されるときの名前です。
このような形で記述します。
```yaml
i_iepa_target_encoder:
_target_: ami.models.model_wrapper.ModelWrapper
model:
_target_: ami.models.vae.Conv2dDecoder
height: 84
width: 84
channels: 3
latent_dim: 512
image_encoder: i_iepa_target_encoder # Alias
```
その関係で、 InferenceWrapperを ModelWrapperに対してシングルトン化しました。これにより、InferenceWrappersDictでも同一のエイリアスが効くようになります。
ModelWrappersDictのキー上書き・削除操作を禁じました。エイリアスを作成する都合上、問題となるためです。
=> Model Namesでモデルにアクセスする際のエイリアス機能を実装

ami/interactions/environments/image_folder_observation_generator.py, tests/interactions/environments/test_image_folder_observation_generator.py
#52 I-JEPAのテスト用のObservationGeneratorクラスを作成しました。
#51 で作成されている experiment config をオーバライドしたexperiment configファイルを作ると良いです。
```yaml
defaults:
- i_jepa
- override /interaction/environment: dummy_image_io
interaction:
environment:
observation_generator: 
_target_: ami.interactions.environments.image_folder_observation_generator.ImageFolderObservationGenerator
root_dir: ${image_data_dir}
image_data_dir: ??? # Specify as command line argument. `python launch.py experiment=<experiment file name> image_data_dir=<path/to/image_data>
task_name: i_jepa_with_dataset
```
=> ImageFolderObservationGeneratorを作成

ami/interactions/environments/unity_environment.py, configs/experiment/unity_sioconv.yaml, configs/interaction/environment/unity.yaml, tests/interactions/environments/test_unity_environment.py
Unity側から送信したフレーム数、位置、オイラー角をcsvに記録
https://github.com/MLShukai/AMIUnityEnvironment/pull/4 が必要
mypyで`SideChannel`の型エラーが出ているので`# type: ignore`をつけてる
```
ami/interactions/environments/unity_environment.py:18: error: Class cannot subclass "SideChannel" (has type "Any")  [misc]
```
=> SideChannelでUnity側から位置情報送信

ami/trainers/dreaming_policy_value_trainer.py, configs/trainers/dreaming_policy_value/default.yaml, tests/trainers/test_dreaming_policy_value_trainer.py
Forward DynamicsやObservation Encoderの学習初期は世界モデルが世界を近似できておらず、その状態で PolicyとValueを学習すると局所解に落ちてしまう問題があった。そのため、初期の学習率を0.0に設定するようにしたことで、この問題を解消した。
次の画像はSimple Worldで学習した際のものである。
学習を開始した後は、行動のエントロピーは維持しつつ、Forward Dynamicsの action lossが低下したため、ある程度規則的な、学習による行動が獲得されたと考える。
=> Dreamerの学習にLR Schedulerを追加し、初期の学習率を0に設定

ami/interactions/io_wrappers/function_wrapper.py, configs/experiment/dreamer.yaml, tests/interactions/io_wrappers/test_function_io_wrapper.py
Japan Streetでの学習において、夜間と昼間で損失が上下する現象が発生していた。夜間は暗くなり、データレンジが小さくなるため損失が小さくなりやすい。その結果 Forward Dynamicsの損失へも影響が出ていた。
観測の平均と分散を1,0に正規化することにより、ある程度解消された。（詳細はDiscordに記述した通り）
=> 観測をnormalize

ami/interactions/agents/multi_step_imagination_curiosity_agent.py, configs/experiment/dreamer_multi_step_imagination.yaml, configs/interaction/agent/curiosity_image_multi_step_imagination.yaml, configs/trainers/dreaming_policy_value/default.yaml, tests/interactions/agents/test_multi_step_imagination_curiosity_agent.py, tests/test_configs.py
1 - Nステップの予測軌道から予測誤差を計算し、その平均を報酬とするAgentを作成しました。
1ステップ前の観測から予測したものの誤差から、Nステップ前から空想してきて予測したもの誤差を算出します。
空想軌道が長くなればなるほど予測は外れやすくなると思ったので、とりあえず指数関数的に減衰させて総和を取り、その係数の総和で割ることで平均を計算しました。
デフォルトでは最大 5秒前からの予想における誤差を加味します。減衰率は `1 - 1 / step数`としています。
時間を分解して考えた時のメモです。
=> 長期的な予測誤差も用いるAgentの実装

ami/models/bool_mask_i_jepa.py, ami/trainers/bool_mask_i_jepa_trainer.py, ami/trainers/components/bool_i_jepa_mask_collator.py, configs/models/bool_mask_i_jepa.yaml, tests/models/test_bool_mask_i_jepa.py, tests/trainers/components/test_bool_i_jepa_mask_collator.py, tests/trainers/test_bool_mask_i_jepa_trainer.py
#59 に関連して、BoolMaskIJEPAPredictorをBoolTargetIJEPAPredictorにリファクタリングした。
スムーズな処理フロー的には、predictorの予測対象「マスク」は「ターゲット」とした方が直感的である。
また、Predictorに予測位置を示すことができれば良いため、ターゲット予測位置にそれを表すベクトルを加算する仕様に変更した。
これにより、Predictorにおいて最大1/2~1/3程度の計算量の低下が見込まれる。
=> Bool Mask版IJEPAのPredictorのマスク仕様の変更と計算量削減のリファクタリング

ami/trainers/bool_mask_i_jepa_trainer.py, ami/trainers/i_jepa_trainer.py, configs/experiment/bool_mask_i_jepa_with_dataset.yaml, configs/experiment/i_jepa_with_dataset.yaml, configs/interaction/environment/image_dataset.yaml, configs/trainers/i_jepa/default.yaml, tests/test_configs.py
I-JEPA をデータセットで学習させ、どのように収束するか確認した際の変更差分。
moving averageの値を変更したり、潜在空間が意味あるものかどうかを確認するために Batch方向に対してstdをとったりして情報を収集した。stdの記録はその後も学習メトリクスに有効と考えたためそのまま残した。
学習データセットは OpenImagesV7のValidationデータセットを用いた。
=> I-JEPAをデータセットで学習

ami/interactions/agents/multi_step_imagination_curiosity_agent.py, ami/trainers/dreaming_policy_value_trainer.py, ami/trainers/ppo_policy_trainer.py, configs/experiment/dreamer_multi_step_imagination_unity.yaml, configs/experiment/world_models_sioconv_lerp_hidden_unity.yaml, configs/models/dreamer.yaml, configs/trainers/dreaming_policy_value/default.yaml, tests/test_configs.py, tests/trainers/test_dreaming_policy_value_trainer.py
#72 
* LRSchedulerではなく Trainerに学習遅延機能を実装しました。
* PPOと比較した際に、Policyの勾配の大きさが小さかったため、returnを時間軸meanからsumに戻しました。
* 学習率を1e-5にしたら安定して学習するようになりました。もっと小さい方がいいかもしれません。
=> Dreamerの未学習問題を修正

scripts/video_action_recorder.py
基礎実験を行う上でデータセットを作成するために、P-AMI<Q>の現在のセンサ、アクチュエータを模倣し、それを操作・記録できるスクリプトを作成しました。
単一のスクリプトで動作します。 pythonバージョンは 3.10以降であれば動くと思われます。 OBSでVRChatのWindowをキャプチャする必要があります。OBS 30以降ではWindowsでも 仮想カメラをまともにキャプチャできるようになってました。
=> pamiqのセンサ・アクチュエータを模倣した形式でVRChatを操作、記録するスクリプトを追加

configs/experiment/i_jepa_sioconv_ppodreamer_multi_step_large.yaml, configs/launch.yaml, scripts/launch.py
PPO DreamerでP-AMI<Q>の最大サイズを実装しました。
どうしても推論速度が10FPSを切ってしまったため、 `torch.set_float32_matmul_precision`を設定し、Tensor Coreを用いるようにして解決しました。
=> PPO Dreamerのラージサイズを実装

ami/interactions/environments/video_folders_image_observation_generator.py, tests/interactions/environments/test_video_folders_image_observation_generator.py
#88 の要件を PR #87 は満たすことができていなかったため、作り直した。
FolderAsVideoクラスの追加で、Folderに多数存在するファイルを一つの連結したVideoとして扱えるようにした。
VideoFoldersImageObservationGeneratorはそのクラスを利用した実装とした。
=> VideoFoldersImageObservationGeneratorを根本的に修正

ami/interactions/environments/unity_environment.py, configs/interaction/environment/unity.yaml, tests/interactions/environments/test_unity_environment.py
#104 UnityEnvironmentの`step`処理を非同期化しました。
同期的に処理する場合、UnityEnvironmentでは次の問題が発生していました。
* `step`を呼ぶ間の時間が大きい場合、Unity側の処理が次フレームまで止まるので動作がカクツク
* 任意のFPSで動作するUnity EnvironmentとAMIの時間進行が一致しない（`env.step`で1フレーム進むため、Unity 30fps, AMI 10fpsという形だと Unity側では 1/3の時間進行になってしまう）
生のUnityEnvironmentは`step`をno-timeで呼ぶと自動的にそのUnityEnvironmentのFPSで`step`メソッドが呼ばれるようintervalが調整されます。
TransformLogChannelを設定しない場合、Unityの指定のFPS(10FPS)にならず、動作が不安定になったのでデフォルトで設定するようになりました。
=> UnityEnvironmentの行動実行を非同期化

ami/interactions/agents/multi_step_imagination_curiosity_agent.py, configs/interaction/agent/curiosity_image_multi_step_imagination.yaml, pyproject.toml
#110 MultiStepImaginationCuriosityAgentにマルチステップ予測の可視化処理を実装しました。デフォルトでは、100ステップ(10秒)ごとに複数予測のarrayを格納し、5000 (500秒)ステップごとに記録します。
=> MultiStepImaginationの可視化処理を実装

ami/models/model_wrapper.py, ami/models/utils.py, ami/threads/training_thread.py, tests/conftest.py, tests/models/test_model_wrapper.py, tests/models/test_utils.py, tests/threads/test_training_thread.py
#110 に関連して、AMI System上でモデルをInferenceThread上のみで使用する機能を実装した。
=> モデルを推論スレッドのみで使用する機能を実装

ami/interactions/io_wrappers/tensor_csv_recorder.py, ami/models/components/deterministic.py, configs/data_collectors/dynamics.yaml, configs/experiment/learn_only_sioconv.yaml, configs/models/learn_only_sioconv.yaml, configs/models/learn_only_sioconv_large.yaml, configs/trainers/forward_dynamics_with_action_reward.yaml, tests/interactions/io_wrappers/test_tensor_csv_recorder.py, tests/test_configs.py
#110 SioConvだけを学習するexperiment configファイルクラスを実装しました。
Videoおよびaction のcsvファイルを用いて学習します。
観測エンコーダは学習済のものを使いますので、I-JEPAの実験が終了した時点での最良モデルを`parameter_file`に設定します。
テスト時にいくつかエラーが出ており、特になぜか CSVFilesPolicyがシリアライズ化されるという現象が発生し、それを解決するためのコードを記述しました。ただ、何かおかしいなと思ってコメントアウトしたら問題が再発生しなくなっていたため、謎です。
=> SioConvだけを学習するexperiment configを追加

ami/interactions/agents/multi_step_imagination_curiosity_agent.py, configs/experiment/learn_only_sioconv.yaml, configs/interaction/agent/curiosity_image_multi_step_imagination.yaml, configs/models/learn_only_sioconv.yaml, tests/interactions/agents/test_multi_step_imagination_curiosity_agent.py
#118 ~~全ての計算機を使用していたため動作確認がまだできていませんが、機能実装は終わったのでPR出します。~~
動作確認取れました。
=> 想像上の軌道の再構成画像のログ機能を追加

ami/models/components/fully_connected_normal.py, ami/models/components/mixture_desity_network.py, tests/models/components/test_fully_connected_normal.py, tests/models/components/test_mixture_density_network.py
Forward Dynamicsの予測誤差が非常に大きい値になりnanになるバグが発生していた。その原因調査の過程で、正規分布の標準偏差が0に近い値に出力される可能性があることに気づいたため、修正した。
標準偏差は初期化後は常に1を返すようにした。
MixtureDensityNetworkの初期の混合割合分布は一様分布になるようにした。
=> FullyConnectedNormalとMixtureDensityNetworkの重み初期化を修正

ami/interactions/agents/multi_step_imagination_curiosity_agent.py
想像したの観測と隠れ状態から出力した行動を使ってしまっていたため、実際に環境に作用させた行動のみを使うように修正した。
=> 想像軌道で実際に環境に作用させたactionを使うよう修正

ami/interactions/agents/multi_step_imagination_curiosity_agent.py, configs/interaction/agent/curiosity_image_multi_step_imagination.yaml
visualizationの処理が `step`メソッドを読みにくくしてしまっていたためメソッドに分割した。
また、 #132 で make_gridを`normalize=True`とするようにしていたため、それも合わせて変更した。
=> MultiStepImaginationCuriosityAgentのvisualization loggingをリファクタリング

configs/experiment/learn_only_sioconv.yaml
バッチサイズと系列長のトレードオフによる性能変化を見るためにconfigを変更しました。
さほど性能に変化は見られませんでしたが、気持ち バッチサイズ1, 系列長を最大にしたものが損失が一番低かったです。
=> batch_sizeでseqlenとsample数がスケールするよう設定

ami/interactions/agents/multi_step_imagination_curiosity_agent.py
複数ステップにかけて予測誤差を計算する場合に何ステップまで考慮するべきかを考えるために、誤差曲線をプロットする処理を追加しました。
=> 予測誤差の曲線をプロットする処理を追加

ami/interactions/environments/actuators/vrchat_osc_discrete_actuator.py, ami/interactions/io_wrappers/tensor_csv_recorder.py, configs/experiment/i_jepa_sioconv_ppo_multi_step.yaml, configs/hydra/default.yaml, configs/interaction/environment/dummy_image_io.yaml, configs/trainers/ppo/default.yaml, scripts/run_experiment_gamma_scale.sh
#146 Policyの収束・発散実験での変更点をPRします．
* ACTION_CHOICES_PER_CATEGORY_MASKED_JUMP_RUNを追加し，去年のAMIの行動設定に近しい設定で実行可能にしました．
* 観測および行動を記録するようにしました．
* 想像上の報酬の記録処理は大きな推論ラグを断続的に生じてしまうため，今回の設計ではデフォルトで無効にしました．
* 割引率gammaが学習の収束速度に大きく影響している事が確認されたため，それを調べるための実行スクリプトを追加しました．
* その他，軽微な修正です．
=> Policyの収束・発散実験での変更

ami/hydra_instantiators.py, ami/models/i_jepa_latent_visualization_decoder.py, ami/models/instantiations.py, configs/experiment/i_jepa_mean_patch_sioconv_ppo_multi_step.yaml, configs/experiment/i_jepa_mean_patch_with_videos.yaml, configs/models/i_jepa_mean_patch.yaml, configs/models/i_jepa_mean_patch_small.yaml, configs/trainers/bool_mask_i_jepa.yaml, scripts/i_jepa_mask_region_simulation.py, tests/models/test_i_jepa_latent_visualization_decoder.py, tests/models/test_instantiations.py, tests/test_configs.py
#157
* I-JEPA単体で学習する際の実装や学習設定ファイルを追加
* Decoderを新規に実装
* infer関数を新規に実装
* Visualization Trainerの学習に時間がかかるようになってしまったため、Context EncoderのVisualizationを無視
* Trainerに`null`を設定可能にし、その場合は無視するようにインスタンス化処理を変更
* 実際にどれだけマスクされるかその割合をシミュレートするスクリプトファイルを実装
* ぱみきゅーが探索的に行動する設定に変更
=> I-JEPAの潜在空間をpatch軸に対してmeanする実装を追加

ami/interactions/environments/actuators/vrchat_osc_discrete_actuator.py, configs/interaction/environment/vrchat_image_discrete.yaml, scripts/video_action_recorder.py, tests/interactions/environments/actuators/test_vrchat_osc_discrete_actuator.py
VRChatOSCDiscreteActuatorを移動や回転速度を設定可能にしました。
ぱみきゅーがグルグル回る行動に収束する現象を調べるためにこの実装を行いました。回転方向の視覚変化の変化率を小さくし、ぱみきゅーが前後左右の移動に収束するようになるのかを調べます。
=> VRChatOSCDiscreteActuatorを移動や回転速度を設定可能に

ami/interactions/environments/actuators/first_order_delay_system.py, ami/interactions/environments/actuators/vrchat_osc_discrete_actuator.py, configs/interaction/environment/vrchat_image_discrete_1st_order_delay.yaml, samples/first_order_delay_system_discrete_actuator_demo.py, tests/interactions/environments/actuators/test_first_order_delay_system.py
#162 issueではなぜかオイラー法で積分する方法を書いていますが、普通に解析解が求まるのでそれで実装しました。
=> 一次遅れ系ステップ応答をシミュレートしたDiscreteActuatorを実装

ami/models/components/audio_patchifier.py, ami/trainers/components/bool_audio_jepa_mask_collator.py, tests/models/components/test_audio_patchifier.py, tests/trainers/components/test_bool_audio_jepa_mask_collator.py
波形のサンプル数に関連した変数名について、`size`や`n_samples`など表記揺れが発生している箇所を、https://github.com/MLShukai/ami-vconf24/blob/main/ami/interactions/environments/sensors/soundcard_audio_sensor.py に倣い`sample_size`という表記に変更
=> 波形のサンプル数に関連した変数名の変更

ami/models/components/sioconvps.py, tests/models/components/test_sioconvps.py
minGRUで使われているParallelScanを取り込んだSioConv
ヘッド毎の忘却が次元数に増えた
=> ParallelScan版SioConv実装
